// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTVhu4H3KCWGavdD2eT4d151HQzqlKj8I',
    appId: '1:1044405617102:web:c4b2f08ff786bb1057eb9f',
    messagingSenderId: '1044405617102',
    projectId: 'warranty-manager-cloud',
    authDomain: 'warranty-manager-cloud.firebaseapp.com',
    storageBucket: 'warranty-manager-cloud.appspot.com',
    measurementId: 'G-062480WQPZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwimgv7H4xkWJGMf2gi-TXKHKenvNFqW4',
    appId: '1:1044405617102:android:957bfde81124a54f57eb9f',
    messagingSenderId: '1044405617102',
    projectId: 'warranty-manager-cloud',
    storageBucket: 'warranty-manager-cloud.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCz7PxBlH8lz3O-ABIykdATBGx57dcb6U0',
    appId: '1:1044405617102:ios:87d00af66dffd1f957eb9f',
    messagingSenderId: '1044405617102',
    projectId: 'warranty-manager-cloud',
    storageBucket: 'warranty-manager-cloud.appspot.com',
    iosClientId: '1044405617102-fgu1heqs64ac9l3jdi3lmnfkbaj2botv.apps.googleusercontent.com',
    iosBundleId: 'net.aravin.warrantyManagerCloud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCz7PxBlH8lz3O-ABIykdATBGx57dcb6U0',
    appId: '1:1044405617102:ios:87d00af66dffd1f957eb9f',
    messagingSenderId: '1044405617102',
    projectId: 'warranty-manager-cloud',
    storageBucket: 'warranty-manager-cloud.appspot.com',
    iosClientId: '1044405617102-fgu1heqs64ac9l3jdi3lmnfkbaj2botv.apps.googleusercontent.com',
    iosBundleId: 'net.aravin.warrantyManagerCloud',
  );
}
